{ lib
, stdenv
, stdenvNoCC
, fetchurl
, runtimeShell
, glibc
, gcc-unwrapped
}:

# oh-my-pi (`omp`) — AI coding agent, prebuilt single-file binary
# from GitHub releases (can1357/oh-my-pi).
# version + per-system hashes live in ./sources.json, regenerated by ./update.sh.
#
# omp is a Bun-compiled standalone executable: the JS payload is appended
# AFTER the ELF, with a trailer at EOF. patchelf/autoPatchelfHook rewrites the
# ELF and shifts that trailer, so Bun stops finding its payload. On Linux we
# keep the binary intact and launch it through the nix loader with a wrapper.

let
  sources = builtins.fromJSON (builtins.readFile ./sources.json);
  src' = sources.systems.${stdenv.hostPlatform.system}
    or (throw "oh-my-pi: unsupported system ${stdenv.hostPlatform.system}");
  loader = if stdenv.hostPlatform.isAarch64
    then "ld-linux-aarch64.so.1"
    else "ld-linux-x86-64.so.2";
in
stdenvNoCC.mkDerivation {
  pname = "oh-my-pi";
  version = sources.version;

  src = fetchurl {
    url = "https://github.com/can1357/oh-my-pi/releases/download/v${sources.version}/${src'.asset}";
    inherit (src') hash;
  };

  dontUnpack = true;

  installPhase = ''
    runHook preInstall
  '' + (if stdenv.isDarwin then ''
    install -Dm755 $src $out/bin/omp
  '' else ''
    install -Dm755 $src $out/libexec/omp
    mkdir -p $out/bin
    cat > $out/bin/omp <<EOF
    #!${runtimeShell}
    exec ${glibc}/lib/${loader} \
      --library-path ${lib.makeLibraryPath [ glibc gcc-unwrapped.lib ]} \
      $out/libexec/omp "\$@"
    EOF
    chmod +x $out/bin/omp
  '') + ''
    runHook postInstall
  '';

  meta = {
    description = "oh-my-pi — AI coding agent for the terminal";
    homepage = "https://github.com/can1357/oh-my-pi";
    license = lib.licenses.mit;
    mainProgram = "omp";
    platforms = builtins.attrNames sources.systems;
  };
}
